sudo: required

language: python

python:
  - 2.7

git:
  depth: 3

before_install:
  - sudo apt-get update
  - sudo apt-get install -y software-properties-common python-software-properties
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe"
  - sudo add-apt-repository -y ppa:adamwolf/kicad-trusty-backports
  - sudo apt-get update
  - sudo apt-get install -y
        build-essential libwxgtk3.0-dev python python-dev
        python-pip python-virtualenv python-gdbm
        python-wxgtk3.0 python-wxgtk3.0-dev xvfb
  - sudo pip install flake8 unlocker
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install:
  - sudo python setup.py install
  - unlocker init && unlocker install
  - python -c "import keepsake.util.misc as u; u.deploy_helper_script()"
  - conda install -c https://conda.anaconda.org/travis wxpython

script:
  - make tests
  - env
  - dpkg -l
  - pip list
