sudo: required

language: python

python:
  - 2.7

git:
  depth: 3

before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential dpkg-dev python2.7-dev libgtk-3-dev
  - sudo apt-get install libjpeg-dev libtiff-dev libsdl1.2-dev libwebkitgtk-3.0-dev
  - sudo apt-get install libgstreamer-plugins-base1.0-dev libnotify-dev freeglut3
  - sudo apt-get install freeglut3-dev libsm-dev libxtst-dev
  - sudo pip install flake8

install:
  - sudo make install

script:
  - unlocker init
  - unlocker install
  - keepsake fix
