sudo: required

language: python

python:
  - 2.7

git:
  depth: 3

before_install:
  - echo "deb http://ro.archive.ubuntu.com/ubuntu/ xenial universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install -y -f gcc-4.8-base libstdc++6
  - wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu55_55.1-7ubuntu0.4_amd64.deb
  - sudo apt install ./libicu55_55.1-7ubuntu0.4_amd64.deb
  - sudo apt-get install -y -f
        build-essential
        dpkg-dev
        python2.7-dev
        libgtk-3-dev
        libjpeg-dev
        libtiff-dev
        libsdl1.2-dev
        libgirepository-1.0-1
        gir1.2-javascriptcoregtk-3.0
        gir1.2-webkit-3.0
        libjavascriptcoregtk-3.0-0
        libjavascriptcoregtk-3.0-dev
        libcairo2
        libfontconfig1
        libgstreamer1.0-0
        libwebp5
        libwebkitgtk-3.0-0
        libwebkitgtk-3.0-dev
        libgstreamer-plugins-base1.0-dev
        libnotify-dev
        freeglut3
        freeglut3-dev
        libsm-dev
        libxtst-dev
        libwxbase3.0-0v5
        libwxgtk3.0-0v5
        python-wxgtk3.0
        python-wxgtk3.0-dev
  - sudo pip install flake8

install:
  - pip list
  - sudo make install

script:
  - unlocker init
  - unlocker install
  - keepsake fix
