sudo: required

language: python

python:
  - 2.7

git:
  depth: 3

env:
  - DISPLAY=:99

before_install:
  - sudo apt-get update
  - sudo apt-get install -y software-properties-common python-software-properties
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe"
  - sudo add-apt-repository -y ppa:adamwolf/kicad-trusty-backports
  - sudo apt-get update
  - sudo apt-get install -y
        build-essential libwxgtk3.0-dev python python-dev
        python-pip python-virtualenv python-gdbm
        python-wxgtk3.0 python-wxgtk3.0-dev xvfb
  - sudo pip install flake8 unlocker

install:
  - Xfvb :99 &
  - env
  - dpkg -l
  - pip list
  - DISPLAY=:99 sudo make install

script:
  - DISPLAY=:99 keepsake
