sudo: required

language: python

python:
  - 2.7

git:
  depth: 3

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - echo "deb http://ro.archive.ubuntu.com/ubuntu/ xenial main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install -y build-essential dpkg-dev python2.7-dev libgtk-3-dev
  - sudo apt-get install -y libjpeg-dev libtiff-dev libsdl1.2-dev libwebkitgtk-3.0-dev
  - sudo apt-get install -y libgstreamer-plugins-base1.0-dev libnotify-dev freeglut3
  - sudo apt-get install -y freeglut3-dev libsm-dev libxtst-dev
  - sudo apt-get install -y python-wxgtk3.0 python-wxgtk3.0-dev
  - sudo pip install flake8

install:
  - pip list
  - sudo make install

script:
  - unlocker init
  - unlocker install
  - keepsake fix
